version: '2'
services:
  proxy:
    build: ./nginx
    image: htpc/proxy:latest
    restart: always
    volumes:
     - ./nginx/mysite.template:/etc/nginx/conf.d/mysite.template    
    ports:
     - "80:80"
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment:
     - NGINX_HOST=toka.dev.com
     - NGINX_PORT=80

  transmission:
    image: dperson/transmission
    restart: always
    ports:
     - "9091:9091"
    volumes:
     - ${HTPC_HOME}/transmission:/var/lib/transmission-daemon/info
     - ${HTPC_HOME}/downloads:/var/lib/transmission-daemon/downloads
     - ${HTPC_HOME}/downloads-incomplete:/var/lib/transmission-daemon/incomplete
    environment:
     - USERID=${HTPC_USER_ID}
     - GROUPID=${HTPC_GROUP_ID}
     - TZ=${HTPC_TIMEZONE}

  couchpotato:
    image: linuxserver/couchpotato
    restart: always
    depends_on:
      - transmission    
    ports:
     - "5050:5050"
    volumes:
     - ${HTPC_HOME}/couchpotato:/config
    environment:
     - TZ=${HTPC_TIMEZONE}
     - PGID=${HTPC_GROUP_ID}
     - PUID=${HTPC_USER_ID}

  sickrage:
    image: linuxserver/sickrage
    restart: always
    depends_on:
      - transmission
    ports:
     - "8081:8081"
    volumes:
     - ${HTPC_HOME}/sickrage:/config
    environment:
     - TZ=${HTPC_TIMEZONE}
     - PGID=${HTPC_GROUP_ID}
     - PUID=${HTPC_USER_ID}

  emby:
    image: emby/embyserver
    restart: always
    ports:
     - "8096:8096"
     - "8920:8920"
     - "7359:7359"
     - "1900:1900"
    volumes:
     - ${HTPC_HOME}/emby:/config
    environment:
     - MB_USER_ID=${HTPC_USER_ID}
     - MB_GROUP_ID=${HTPC_GROUP_ID}
     - TZ=${HTPC_TIMEZONE}
     - AUTO_UPDATES_ON=true
