version: '2'
services:
  data:
    image: tianon/true
    container_name: data  
    restart: always
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /etc/timezone:/etc/timezone:ro
     - ~/.htpc/media:/media   
     - ~/.htpc/media/Videos/Movies:/movies
     - ~/.htpc/media/Videos/TVShows:/tv
     - ~/.htpc/media/Music:/music
     - ~/.htpc/downloads:/downloads
     - ~/.htpc/downloads-incomplete:/downloads-incomplete

  proxy:
    build: nginx
    container_name: proxy
    restart: always
    ports:
     - "80:80"
    extra_hosts:
     - "emby:172.18.0.1"

  transmission:
    image: dperson/transmission
    container_name: transmission
    restart: always
    ports:
     - "9091:9091"
    volumes:
     - ~/.htpc/transmission:/var/lib/transmission-daemon/info
     - ~/.htpc/downloads:/var/lib/transmission-daemon/downloads
     - ~/.htpc/downloads-incomplete:/var/lib/transmission-daemon/incomplete
    environment:
     - USERID=1000
     - GROUPID=1000
     - TZ=America/Sao_Paulo

  couchpotato:
    image: linuxserver/couchpotato
    container_name: couchpotato
    restart: always
    depends_on:
      - transmission    
    ports:
     - "5050:5050"
    volumes:
     - ~/.htpc/couchpotato:/config
    volumes_from:
     - data

    environment:
     - TZ=America/Sao_Paulo
     - PGID=1000
     - PUID=1000

  sickrage:
    image: linuxserver/sickrage
    container_name: sickrage
    restart: always
    depends_on:
      - transmission
    ports:
     - "8081:8081"
    volumes:
     - ~/.htpc/sickrage:/config
    volumes_from:
     - data
    environment:
     - TZ=America/Sao_Paulo
     - PGID=1000
     - PUID=1000

  emby:
    image: emby/embyserver
    container_name: emby
    restart: always
    network_mode: host
    ports:
     - "8096:8096"
     - "8920:8920"
     - "7359:7359"
     - "1900:1900"
    volumes:
     - ~/.htpc/emby:/config
    volumes_from:
     - data
    environment:
     - MB_USER_ID=1000
     - MB_GROUP_ID=1000
     - TZ=America/Sao_Paulo
     - AUTO_UPDATES_ON=true

  volumes:
    redis-data:
      driver: local
